# <font color='saddlebrown'>Data Cleaning</font>

***
***

### <font color='saddlebrown'>Import packages</font>

In [24]:
# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")


In [2]:
#for easy access to path
import os
import sys

#importing packages for data manuplation and visualization
import numpy as np
import pandas as pd

# Visualization
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import Image
from IPython.display import Markdown, display, Image, display_html
from scipy.stats import skew

In [3]:
import matplotlib.pyplot as plt
from IPython.display import Image
from IPython.display import Markdown, display, Image, display_html
from scipy.stats import skew

In [4]:
# Visualization df
%matplotlib inline
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [5]:
sys.path.append(os.path.abspath(os.path.join('../scripts')))

In [10]:
sys.path.append(os.path.abspath(os.path.join('../data')))

In [22]:
from data_preview import DataPreview 
from data_loader import *
from data_cleaner import CleanDf

In [23]:
#object creation
data_df=DataPreview(df)
#CleanDf(df)

***
***

### <font color='saddlebrown'>Data descriptions</font>

Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass. They describe characteristics of the cell nuclei present in the image. The mean, standard error and "worst" or largest of these features were computed for each image, resulting in 30 features. For instance, field 3 is Mean Radius, field 13 is Radius SE, field 23 is Worst Radius.All feature values are recoded with four significant digits.

*** 
                                    The following are data descriptions.
***

Attribute Information:

- ID number
- Diagnosis (M = malignant, B = benign)

Ten real-valued features are computed for each cell nucleus:

- ID number
- Diagnosis(M=malignant, B=benign)
- radius(mean of distances from center to points on the perimeter)
- texture(standard deviation of gray - scale values)
- perimeter
- area
- smoothness(local variation in radius lengths)
- compactness(perimeter ^ 2 / area - 1.0)
- concavity(severity of concave portions of the contour)
- concave points(number of concave portions of the contour)
- symmetry
- fractal dimension("coastline approximation" - 1)

In [25]:
#df_new=load_df_from_csv("../data/data.csv")
df = pd.read_csv("../data/data.csv")

In [26]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  fractal_dimension_mean  radius_se  texture_se  perimeter_se  \
0         0.2419                 0.07871     1.0950      0.9053         8.589   
1         0.1812                 0.05667     0.5435      0.7339         3.398   
2         0.2069                 0.05999     0.7456      0.7869         4.585   
3         0.2597                 0.09744     0.4956      1.1560         3.445   
4         0.1809                 0.05883     0.7572      0.7813         5.438   

   area_se  smoothness_se  compactness_se  concavity_se  concave points_se  \
0   153.40       0.006399         0.04904       0.05373            0.01587   
1    74.08       0.005225         0.01308       0.01860            0.01340   
2    94.03       0.006150         0.04006       0.03832            0.02058   
3    27.23       0.009110         0.07458       0.05661            0.01867   
4    94.44       0.011490         0.02461       0.05688            0.01885   

   symmetry_se  fractal_dimension_se  radius_worst  texture_worst  \
0      0.03003              0.006193         25.38          17.33   
1      0.01389              0.003532         24.99          23.41   
2      0.02250              0.004571         23.57          25.53   
3      0.05963              0.009208         14.91          26.50   
4      0.01756              0.005115         22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN

In [27]:
#check if the data has null values
missing = data_df.percent_missing(df)

The dataset contains 3.03 % missing values.


> The store data has <font color='red'>3.03 %</font> missing values.

In [28]:
#get the missing percenatage in each columns
data_df.missing_values_table()

total_missing_values missing_percentage
Unnamed: 32                               569            100.0 %
compactness_se                              0              0.0 %
fractal_dimension_worst                     0              0.0 %
symmetry_worst                              0              0.0 %
concave points_worst                        0              0.0 %
concavity_worst                             0              0.0 %
compactness_worst                           0              0.0 %
smoothness_worst                            0              0.0 %
area_worst                                  0              0.0 %
perimeter_worst                             0              0.0 %
texture_worst                               0              0.0 %
radius_worst                                0              0.0 %
fractal_dimension_se                        0              0.0 %
symmetry_se                                 0              0.0 %
concave points_se                           0              0.0 %
concavity_se                                0              0.0 %
id                                          0              0.0 %
diagnosis                                   0              0.0 %
area_se                                     0              0.0 %
perimeter_se                                0              0.0 %
texture_se                                  0              0.0 %
radius_se                                   0              0.0 %
fractal_dimension_mean                      0              0.0 %
symmetry_mean                               0              0.0 %
concave points_mean                         0              0.0 %
concavity_mean                              0              0.0 %
compactness_mean                            0              0.0 %
smoothness_mean                             0              0.0 %
area_mean                                   0              0.0 %
perimeter_mean                              0              0.0 %
texture_mean                                0              0.0 %
radius_mean                                 0              0.0 %
smoothness_se                               0              0.0 %

>`Unnamed: 32` has <font color='red'>100 % </font> missing values need to be dropped.	

In [29]:
df.shape

(569, 33)

>The dataset has `569` rows and `33` columns.

In [33]:
#lising the columns
df.columns.tolist()

['id',
 'diagnosis',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst',
 'Unnamed: 32']

In [45]:
#object creation
cleaner_df=CleanDf(df)

In [47]:
cleaner_df.remove_unwanted_columns('Unnamed: 32')

In [51]:
#lising the columns
df.columns.tolist()

['id',
 'diagnosis',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

> `Unnamed: 32` column droped .

In [55]:
# search for duplicate rows and drop them
cleaner_df.remove_duplicates()

### <font color='saddlebrown'>Save clean CSV</font>

In [56]:
# save the clean dataframe to a csv file
df.to_csv('../data/clean_data.csv', index=False)

>`Clean data produced .`

>`Data cleaning completed .`

***
***